### ISSUE TITLE
Add a failure analyzer for Hibernate bootstrap failure

### ISSUE THREAD

**Issue by kryger** [spring-projects/spring-boot#1573]
I'm trying to make my application's configuration as foolproof as possible by failing as soon as missing properties are detected. My app has two `DataSource`s so I followed the [Configure Two DataSources how-to](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources). This works nicely, but gets confusing if the properties with given prefix aren't there (this would happen if the production `.yml` file was missing or didn't contain the expected DB credentials). In a JPA application this causes:

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
(...snip...)
        at demo.Application.main(Application.java:14)
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:104)
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:71)
(...snip...)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:842)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1627)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1564)
        ... 14 more

```

I'd expect something more precise like "Couldn't initialise DataSource with prefix=datasource.secondary; check your config!".

---

I tried it with a JDBC starter too and it... quietly succeeds, initializing the `DataSource` with `null`s - not sure if it's a different underlying issue.

Haven't done more investigation, may try to debug to narrow it down a bit if needed. Submitted repros for both problems to spring-boot-issues.

**Comment by bozzwin** [comment]
I did a review of this issue. I analyzed the case with jpa dependencies and the stack trace is thrown because you forgot to add one properties in configuration file, for instance:

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

After that I got another exception:

java.sql.SQLException: The url cannot be null
	at java.sql.DriverManager.getConnection(DriverManager.java:556) ~[na:1.7.0_79]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_79]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:308) ~[tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) ~[tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:716) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648) [tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468) [tomcat-jdbc-8.5.4.jar:na]

which means that user should add a few properties describing data source: 

spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

I would like to improve that issue but I need full description of how it should behave.

**Comment by rzymek** [comment]
First of all - this issue is still valid after updating to version to 1.5.1.RELEASE. (This updates hibernate dependency to 5.0.11.Final)

I'd say the main issue here is how hibernate itself handles empty config. Ever since at least [4.0.1](https://github.com/rzymek/hibernate-minimal-project/blob/4.0.1/output.txt) up to the current [5.2.8](https://github.com/rzymek/hibernate-minimal-project/blob/5.2.8/output.txt), hibernate-core complains about not having a dialect when [run with an empty config](https://github.com/rzymek/hibernate-minimal-project/blob/4.0.1/src/main/java/demo/Main.java).

When I [modify hibernate to use a default dialect on error](https://github.com/rzymek/hibernate-orm/commit/34da22293fd0655fd41b48a1b457f1f5fa3754ac), your spring-boot project's output becomes:

```
2017-02-26 21:54:39.203  WARN 27618 --- [           main] o.a.tomcat.jdbc.pool.PooledConnection    : Not loading a JDBC driver as driverClassName property is null.
2017-02-26 21:54:39.214 ERROR 27618 --- [           main] o.a.tomcat.jdbc.pool.ConnectionPool      : Unable to create initial connections of pool.

java.sql.SQLException: The url cannot be null
	at java.sql.DriverManager.getConnection(DriverManager.java:649) ~[na:1.8.0_92]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_92]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PcooledConnection.java:308) ~[tomcat-jdbc-8.5.11.jar:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) ~[tomcat-jdbc-8.5.11.jar:na]

```
(just like when `spring.jpa.database-platform` is set)

I'd say this isn't really a spring issue, but a hibernate one. At least concerning the jpa case.
I'll be submitting a pull request to [hibernate-orm](https://github.com/hibernate/hibernate-orm) to make it behave better on empty config.

**Comment by philwebb** [comment]
Relates to #9219

**Comment by ezraroi** [comment]
Is this issue still relevant or it was closed with #9219?

**Comment by snicoll** [comment]
#9219 was closed as a duplicate of this one. Yes, it is still relevant.

**Comment by ezraroi** [comment]
Great, will work on it. Should be fixed on the master?

**Comment by snicoll** [comment]
Yes, thank you.

**Comment by amutsch** [comment]
Hibernate does not require a dialect.  If it can connect to the DB without issue it will determine the proper dialect.  The issue comes when hibernate can not connect then its first assumption is it doesn't have a dialect for the DB.  In hibernates current state it is not common for it to not be able to determine the dialect.  I agree with @rzymek that this is more of a hibernate issue since invalid credentials can identify as missing dialect property.

**Comment by exijn** [comment]
Hi, I’d be interested in revisiting this issue.

Since it predates the current Spring Boot and Hibernate versions, I would first create a minimal reproduction against the current `main` branch and identify whether there is still a stable exception or cause pattern that a `FailureAnalyzer` can handle reliably.

If the problem is still reproducible, I would add focused analyzer tests and ensure that the analyzer does not match unrelated Hibernate bootstrap failures.

Is this still a direction the team would welcome as a contribution?

**Comment by wilkinsona** [comment]
Thanks, @hej090224. 

> Since it predates the current Spring Boot and Hibernate versions, I would first create a minimal reproduction against the current main branch and identify whether there is still a stable exception or cause pattern that a FailureAnalyzer can handle reliably.

This sounds good to me. Once we've confirmed that it's still a problem and know what the error is with modern Hibernate, we can take things from there.

**Comment by exijn** [comment]
## Investigation results on current `main`

I investigated the bootstrap failure scenarios discussed in this issue against:

- Spring Boot commit: `222783aee4a5a9ca07e4f78a5e593a6ebb43f31a`
- Spring Boot version: `4.2.0-SNAPSHOT`
- Hibernate ORM version: `7.4.5.Final`
- Java: `25.0.2` (Windows)
- Environment: local H2 TCP server for successful and authentication cases; no external database or Docker required

The reproductions used the real Spring Boot `ApplicationContextRunner` with `DataSourceAutoConfiguration`, `HibernateJpaAutoConfiguration`, and `TransactionAutoConfiguration`. No Hibernate or JDBC exceptions were mocked.

| Scenario | Result | Top-level exception | Relevant cause/message | Stable analyzer signal |
| --- | --- | --- | --- | --- |
| Normal H2 connection and automatic dialect detection | PASS | none | Context started successfully | No failure to analyze |
| Connection refused | reproduced | `BeanCreationException` | `ServiceException` -> `HibernateException`: `Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)` | `ServiceException`/`HibernateException` and this message are stable, but the JDBC `ConnectException` is logged and is not retained in the startup cause chain |
| Wrong username | reproduced | `BeanCreationException` | Same Hibernate dialect message; Hibernate logs `AuthException: Unable to obtain isolated JDBC connection [Wrong user name or password ...]` | Same signal as an unavailable database; the startup exception does not distinguish authentication from connectivity |
| Wrong password | reproduced | `BeanCreationException` | Same Hibernate dialect message; Hibernate logs the authentication failure | Same signal as connection refusal |
| Missing/unloadable JDBC driver | reproduced | `UnsatisfiedDependencyException` | DataSource creation fails before Hibernate: `Cannot load driver class: no.Driver` | No Hibernate dialect signal; this is a DataSource/bootstrap failure |
| URL/driver mismatch (PostgreSQL driver selected for an H2 URL) | reproduced | `UnsatisfiedDependencyException` | DataSource creation fails before Hibernate: `Cannot load driver class: org.postgresql.Driver` | No Hibernate dialect signal |
| Explicit non-existent Dialect class | reproduced | `BeanCreationException` | `ServiceException` -> `StrategySelectionException` -> `ClassLoadingException` -> `ClassNotFoundException`; `Unable to resolve name [no.such.Dialect] as strategy [org.hibernate.dialect.Dialect]` | A different, more specific Hibernate signal; it should not be confused with metadata/connection failure |
| General Hibernate bootstrap setting error (invalid `hibernate.hbm2ddl.auto`) | reproduced | `BeanCreationException` | `IllegalArgumentException: Unrecognized 'hibernate.hbm2ddl.auto' setting: 'not-a-mode'` | No dialect signal; a dialect analyzer would risk a false positive if it matched generic Hibernate failures |

For the refused-connection and authentication cases, the useful JDBC details are present in Hibernate's log output (for example, `Connection refused` or `Wrong user name or password`), but the exception propagated by the JPA bootstrap is the same dialect-resolution failure. This is the disconnect described in the earlier discussion: the exception that stops startup does not reliably preserve the actual database failure.

### Hibernate-side status

The Hibernate-side change mentioned in the original discussion was found as [hibernate/hibernate-orm#1807](https://github.com/hibernate/hibernate-orm/pull/1807), for HHH-11522. It proposed changing the empty-configuration behavior so that the eventual connection failure would be reported instead of the missing-dialect message. The PR is closed and unmerged (`merge_commit_sha` is present only for its last commit); its commit is not an ancestor of current Hibernate `main`. I found no merged follow-up for that change. The old `rzymek/hibernate-orm` commit `34da22293fd0655fd41b48a1b457f1f5fa3754ac` is a fork commit, not evidence of an upstream Hibernate release containing the change.

Current Hibernate has improved the wording from the historical `Access to DialectResolutionInfo cannot be null...` message to the stable `Unable to determine Dialect without JDBC metadata...` wording, but the underlying loss of the connection failure is still observable in these reproductions.

### Assessment

There is a narrow, repeatable Hibernate signal for the metadata/dialect failure: `ServiceException` with a nested `HibernateException` and the current message. It covers at least connection refusal and invalid credentials, but it cannot identify which of those caused the failure because Hibernate does not retain the JDBC cause in the startup chain. Matching the message would therefore support only generic guidance and would be sensitive to Hibernate wording changes.

The driver cases already fail during DataSource creation, while explicit Dialect and other Hibernate configuration errors have different exception types and messages. A single broad analyzer would consequently be prone to false positives. The evidence also supports considering a Hibernate-side change that preserves or surfaces the JDBC connection exception. I have not implemented a Spring Boot analyzer or any product/documentation change.

### Verification

- `./gradlew.bat :module:spring-boot-hibernate:test --tests org.springframework.boot.hibernate.autoconfigure.Investigation1573Tests --no-daemon -g C:\\gradle1573` — PASS; temporary real-context reproduction completed
- `./gradlew.bat :module:spring-boot-hibernate:test :module:spring-boot-jdbc:test --no-daemon -g C:\\gradle1573` — PASS
- `git diff --check` — PASS
- `git status --short` — clean after removing the temporary test and dependency

The regular Gradle user home could not be used because its global `org.gradle.java.home` points to a temporary JDK 26 installation without `JAVA_COMPILER`; the isolated Gradle user home and Java 25 JDK were used instead. No external database, Docker, or cloud resource was used, so vendor-specific server behavior was not investigated.

Based on these results, would you prefer a narrowly scoped analyzer for the metadata/dialect failure with generic connection guidance, or should the loss of the JDBC cause be addressed on the Hibernate side first?
