### ISSUE TITLE
Thymeleaf templates preceded by a slash are found when running in an IDE but not when running from a jar

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1744]
See http://stackoverflow.com/questions/26493831/spring-boot-thymeleaf-not-resolving-fragments-after-packaging. I'm not sure that there's anything we can do but I'd like to investigate.

**Comment by izeye** [comment]
If it's a common mistake, I think giving a warning message would be helpful.

**Comment by opensource21** [comment]
Just as an extra information. I have a similar [issue](http://stackoverflow.com/questions/32936108/thymeleaf-template-not-found-with-embedded-tomcat) and there it works in the IDE and Tomcat. So I think the default jdk is inconsistent, would be great to get a warning.

**Comment by Dluquem** [comment]
Yo tenia el mismo problema, la solución la encontré en este link. https://stackoverflow.com/questions/27249078/spring-boot-gives-templateinputexception-error-resolving-template-when-runnin

Okay, I found where you have to take a close look. In your Controller classes, when you use @RequestMapping on class, no leading slash (e.g. @RequestMapping("property")). On Method you need a leading slash (e.g. @GetMapping("/list")) and the return value no leading slash (e.g. return "property/list";)

An Example Snippet

@Controller
@RequestMapping("property")
public class PropertyController {
    @NonNull PropertyService service;

    @GetMapping("/list")
    public String list() {
        return "property/list";
    }
}

**Comment by AleixAlcover** [comment]
I'm having the same problem, but none of the solutions explained here have worked for me. Deploying my jar into Pivotal Web Services it works, therefore I guest there is some configuration or whatever, that they detect and correct. But the same jar running locally or with other cloud providers doesn't work.

Mine is a Spring Boot application using Thymeleaf 2.1.6 as template resolver, which works fine when debugging from NetBeans. I build the jar with Maven.

Some of my controllers could have the double slash problem, but I've corrected them and the problem persists. I've placed this question in Stack Overflow, with some extracts of my code:

[https://stackoverflow.com/questions/48400967/error-resolving-template-with-spring-boot-using-thymeleaf-packaged-in-a-jar](https://stackoverflow.com/questions/48400967/error-resolving-template-with-spring-boot-using-thymeleaf-packaged-in-a-jar)

Any help would be very much appreciated,
Aleix

**Comment by evertones** [comment]
Is this issue resolved?
I've tried with version `1.5.10` and seems to be still happening.

I have the following code:

    @Controller
    public TestController {
        @RequestMapping(path= "/client/add", method = RequestMethod.GET)
        public String add() {
            return "/client/add";  // STARTS WITH A SLASH
        }
    }

It works starting with Spring Boot using Maven: `./mvnw spring-boot:run`.
It does not work with the `jar`: `java -jar myapp.jar`.

If I change the code above to return the template without the slash in the beginning, it works on both:

    @Controller
    public TestController {
        @RequestMapping(path= "/client/add", method = RequestMethod.GET)
        public String add() {
            return "client/add";  // DOES NOT START WITH A SLASH
        }
    }

Is it the expected behaviour or this issue should've fixed that?

**Comment by AleixAlcover** [comment]
When you return the URI starting with a slash, you always send a double slash. The difference is that starting with Spring the file system deals with this issue, which doesn't do the JVM, when you run the .jar.

**Comment by oratengG4S** [comment]
I'm using Spring Boot 2.0.0.RELEASE and I'm experiencing this, I've tried removing slashes on my RequestMapping but I'm still getting HTTP 500. Is there a solution for this?

**Comment by AleixAlcover** [comment]
Have you checked the links in the .html (Thymeleaf template)? There you could be generating double slashes as well.
