### ISSUE TITLE
Logback config not being honored when SpringApplication.run() is invoked

### ISSUE THREAD

**Issue by ShawnTuatara** [spring-projects/spring-boot#196]
Hi... I have run into an odd issue trying to troubleshoot an issue within my application. I was wanting to see some debug output so I setup my logback.xml file but no matter what I did I couldn't get debug output to show. Eventually I created the below code block to validate what logback.xml was being used. At the initial startup the log context is great and uses my configured logback information. Unfortunately after the spring context has been loaded and the application is running the log context has changed to the default spring boot logback configuration. How can I correct this or is this an issue with spring boot?

```
@ComponentScan
@EnableAutoConfiguration
public class Application {
    public static void main(String[] args) {
        LoggerContext loggerContext = ((ch.qos.logback.classic.Logger) log).getLoggerContext();
        URL mainURL = ConfigurationWatchListUtil.getMainWatchURL(loggerContext);
        log.info("Logback used '{}' as the configuration file.", mainURL);
        Level level = loggerContext.getLogger(Logger.ROOT_LOGGER_NAME).getLevel();
        log.info("Root logger level is: {}", level);

        SpringApplication.run(Application.class, args);

        URL mainUrlAfter = ConfigurationWatchListUtil.getMainWatchURL(loggerContext);
        log.info("Logback used '{}' as the configuration file.", mainUrlAfter);
        Level levelAfter = loggerContext.getLogger(Logger.ROOT_LOGGER_NAME).getLevel();
        log.info("Root logger level is: {}", levelAfter);
    }
}
```

output

```
2014-01-07 15:25:44.983  INFO   --- [           main] com.testapp.Application  : Logback used 'file:/C:/Development/Workspaces/git/testapp/target/classes/logback.xml' as the configuration file.
2014-01-07 15:25:44.988  INFO   --- [           main] com.testapp.Application  : Root logger level is: DEBUG

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v0.5.0.BUILD-SNAPSHOT)

2014-01-07 15:25:45.394  INFO 11708 --- [           main] com.testapp.Application  : Starting Application on TESTMACHINE with PID 11708 (C:\Development\Workspaces\git\testapp\target\classes started by sclark)
2014-01-07 15:25:45.429  INFO 11708 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@10d4159f: startup date [Tue Jan 07 15:25:45 PST 2014]; root of context hierarchy
...
2014-01-07 15:25:50.688  INFO 11708 --- [           main] com.testapp.Application  : Started Application in 5.52 seconds (JVM running for 6.053)
2014-01-07 15:25:50.689  INFO 11708 --- [           main] com.testapp.Application  : Logback used 'jar:file:/C:/Development/Repo/org/springframework/boot/spring-boot/0.5.0.BUILD-SNAPSHOT/spring-boot-0.5.0.BUILD-SNAPSHOT.jar!/org/springframework/boot/logging/logback/logback.xml' as the configuration file.
2014-01-07 15:25:50.689  INFO 11708 --- [           main] com.testapp.Application  : Root logger level is: INFO
```

**Comment by RobHK** [comment]
Hello,

Is this fix in a released version please? I am having the same issue using the spring-boot-starter-parent.

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.2.4.RELEASE</version>
    </parent>

**Comment by wilkinsona** [comment]
As [confirmed above](https://github.com/spring-projects/spring-boot/issues/196#issuecomment-32955229) this issue was fixed in 1.0.0.RC1. If you believe you've found a similar problem, please open a new issue with a description and details of how to recreate it.

**Comment by RobHK** [comment]
OK thanks I'll check my config again.

**Comment by MalathiBoggavarapu** [comment]
> 
Thanks a ton for reporting this issue. I am facing this issue today and was pissed off. Fortunately i found your post and realized what the actual issue is. But this issue is closed and seems like it is resolved. But i still face the same issue with spring-boot-starter latest 2.7.1.

**Comment by wilkinsona** [comment]
@MalathiBoggavarapu We're not aware of any problems with logback.xml in Spring Boot 2.7. If you believe you've found one then please open a new issue with a description of it and details of how to recreate it.

**Comment by aniketpandit-sophos** [comment]
I am same issue in spring boot 2.7 when using central BOM
