### ISSUE TITLE
Add support for streaming responses from actuator web endpoints

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21308]
https://github.com/spring-projects/spring-boot/pull/21296 describes a use case for streaming a response from an actuator web endpoint rather than buffering the whole response in memory and then writing it out. While it's already possible with a web-stack-specific endpoint, such as `@RestControllerEndpoint`, it would be good to have something that's web-stack-agnostic that can be returned from an endpoint operation as `Resource`, for example, can be used today.

**Comment by bric3** [comment]
Hi I just came from #21296, I started to use spring actuators endpoint to expose prometheus metrics. However I noticed a noticeable increase in humongous allocations (G1GC), almost all due to spring related classes. This is causing regular unresponsiveness in the application(s) (pauses up-to ~100ms).

![image](https://user-images.githubusercontent.com/803621/91177362-e4dee900-e6e3-11ea-8f0a-d1b297e9b952.png)

There's a few Spring Framework in cause too. Should I open a ticket there ?

I can share the flamegraph privately, as there is other _private flames_ triggering humongous allocations.

**Comment by wilkinsona** [comment]
Three of the humongous allocations appear to be related to Prometheus so they should be addressed by the enhancement that's proposed here. The other two appear to be released to HTTP message conversion in Spring Framework. I think it would be worth opening a Framework issue for those so that they can investigate.

**Comment by bric3** [comment]
OK let's do it. Thanks for the quick feedback.

**Comment by bric3** [comment]
While the stack is pointing to springboot actuator, it leverages the prometheus simpleclient `TextFormat.write004`. I think the issue could be resolved by passing a StringWriter with enough capacity maybe as a function of the number of metrics. And by not returning a `String`, but then the `StringWriter` may be not the right type form the start.

**Comment by ITman1** [comment]
Still an issue with new Spring and Spring boot, having this payload on our side is definitelly a weird/bug, but still Spring could handle streaming in better way:

![Image](https://github.com/user-attachments/assets/23321162-d327-45ad-a4cf-7ba3fc9d96c3)

**Comment by ITman1** [comment]
Yes, it is related, high CPU time and GC pauses are symtoms of too large payloads/responses allocated on Heap due to usage of `byte[]` (`ByteArrayOutputScream`) in Prometheus Scrape endpoint. Heap dump is actually crash dump which was dumped after reaching `OutOfMemoryError`. Anyway I just found a root cause why huge payloads were even created - https://github.com/spring-projects/spring-amqp/issues/2914.

I am only noting here that crash place was in Spring Boot Prometheus Scape Endpoint due to lack streaming:

![Image](https://github.com/user-attachments/assets/52f952f3-cff5-4974-aab8-84dc8e8c098a)

So I am only suggesting performance improvement here as this usually means issue somewhere else, now in Spring AMQP, but still in standard cases Prometheus scape endpoint might produce payloads around 1MB, reaching already half of G1 region size when having <4GB of heap and I think it is better to stream such payloads instead of puting those on heap.

**Comment by bclozel** [comment]
We'll consider this performance improvement. As for the Spring AMQP issue, this looks like a cardinality explosion to me, so not strictly related to large responses. Even with small responses, unbounded metric tags will overflow memory.

**Comment by marschall** [comment]
> While the stack is pointing to springboot actuator, it leverages the prometheus simpleclient `TextFormat.write004`. I think the issue could be resolved by passing a StringWriter with enough capacity maybe as a function of the number of metrics. And by not returning a `String`, but then the `StringWriter` may be not the right type form the start.

The latest Prometheus Java client versions should avoid the single `char` writes to `OutputStreamWriter`

https://github.com/prometheus/client_java/pull/1241
https://github.com/prometheus/client_java/pull/1248
