### ISSUE TITLE
JarFileWrapper may cause many FinalReferences causing GC pressure

### ISSUE THREAD

**Issue by HzjNeverStop** [spring-projects/spring-boot#28042]
Environment：spring boot 2.5.4 + jdk8
Create a bean to continue load class which could not be found,than use java -jar start springboot fatjar
```
@Component
public class TestClass implements InitializingBean {
    @Override
    public void afterPropertiesSet() throws Exception {
        new Thread(() -> {
            while (true) {
                try {
                    Class.forName("com.test.error.NotClassFound");
                } catch (ClassNotFoundException e) {
                    //ignore
                }
            }
        }).start();
    }
}
```
many org.springframework.boot.loader.jar.JarFileWrapper will be create which increase FinalReference time in gc:
![20210917132511](https://user-images.githubusercontent.com/19757574/133729189-db5ec7b5-d0be-4773-bb5d-158e74b37efe.jpg)

when update spring boot version to 2.1.13，it's ok：
![20210917132520](https://user-images.githubusercontent.com/19757574/133729263-d2f93996-e2f1-4f68-8224-acfa0077a913.jpg)

In normal it will not happen because LaunchedURLClassLoader has package cache，but it will happen when so bug trigger many nonexistent class load.

**Comment by wilkinsona** [comment]
Thanks for the report. I have reproduced the behaviour that you have described. I suspect that the changes for https://github.com/spring-projects/spring-boot/issues/22991 are the cause. It was intended to fix a problem that's specific to Java 11 but it looks as if it may have regressed things on Java 8. Running on Java 8, the peak memory footprint of `JarFileWrapper` is around 10x the peak that I see on Java 11.

**Comment by wilkinsona** [comment]
This may have been reported previously in https://github.com/spring-projects/spring-boot/issues/23505 but there wasn't enough information to diagnose the problem.

**Comment by wilkinsona** [comment]
@philwebb What's your take on this one. Short of having different code for Java 8 and Java 11 (which is tricky as we're sub-classing), I'm not sure what the best approach is here.

**Comment by philwebb** [comment]
I'm really not sure how to fix this one. We do have #26745 open as well.

**Comment by wilkinsona** [comment]
👍 LGTM.

**Comment by fankaifeng** [comment]
> 👍 LGTM.hello,I had the same problem, What should I do

**Comment by wilkinsona** [comment]
@fankaifeng As far as we know, this problem was fixed in Spring Boot 2.4.12. If you're using a newer version of Spring Boot and the problem is still occurring, please open a new issue and provide a complete yet minimal sample that reproduces it.

**Comment by fankaifeng** [comment]
Why is the problem version 2.5.4 raised by HzjNeverStop not compatible after 2.4.12, our version is 2.3.12.RELEASE, do not want to upgrade, how to solve it

**Comment by bclozel** [comment]
@fankaifeng it's been fixed in 2.5.6 as well, see #28356.
Spring Boot 2.3.x has been [out of open source support for 2+ years and of commercial support for a year now](https://spring.io/projects/spring-boot#support). We won't release new 2.3.x versions; please upgrade to a supported Spring Boot version.

**Comment by wilkinsona** [comment]
The problem described in this issue cannot be solved without upgrading. Also, please note that you're using [an unsupported version of Spring Boot](https://spring.io/projects/spring-boot#support). You should upgrade to 2.7.x or later as soon as possible.

**Comment by helloworldtang** [comment]
2.5.2  also have the problem:
org.springframework.boot.loader.jar.JarFileWrapper may cause many FinalReference when running on Java 8

jdk version: 1.8.0_144
spring boot:2.5.2 

from dump ：      
<img width="1570" alt="image" src="https://github.com/spring-projects/spring-boot/assets/13701989/0094a60e-f79e-4f38-b140-cd287bbd6df6">


<img width="707" alt="image" src="https://github.com/spring-projects/spring-boot/assets/13701989/ed30ad2a-121c-4499-b575-67c4797f1ca2">

**Comment by wilkinsona** [comment]
@helloworldtang That is to be expected as this issue was not fixed until 2.5.6.
