### ISSUE TITLE
TestcontainersLifecycleBeanPostProcessor does not work correctly with scoped beans

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#35786]
I’ve been playing around with several examples using Spring Boot Testcontainers at Development time and last night I noticed those are not working as expected with `@RestartScope`. IIRC [this example](https://github.com/eddumelendez/spring-boot-pulsar-testcontainers-reusable-mode/blob/main/producer/src/test/java/com/example/producer/ProducerApplicationTests.java#L13-L31) used to work in the past, download the image, start the container and so on. I also tried something similar to what’s mentioned in the [docs](https://docs.spring.io/spring-boot/docs/3.1.0/reference/htmlsingle/#features.testing.testcontainers.at-development-time.dynamic-properties) but the image is not downloaded at all in [this example](https://github.com/eddumelendez/spring-boot-rabbitmq-testcontainers-reusable-mode/blob/main/producer/src/test/java/com/example/producer/ProducerApplicationTests.java#L12-L29) if `@ServiceConnection` is removed. It works as expected without `@RestartScope`

**Comment by nedimAT** [comment]
Hello @philwebb, i would like to fix this. Please assign it to me.

**Comment by philwebb** [comment]
Thanks @nedimAT, I've assigned the issue to you. I've no idea if it's an easy or difficult fix so feel free to comment here if you don't get anywhere.

**Comment by nedimAT** [comment]
Hello @eddumelendez, for me the rabbitmq me works as expected. Removing the `@ServiceConnection` Annotation means you have to setup the properties yourself, see [docs dynamic-properties](https://docs.spring.io/spring-boot/docs/3.1.0/reference/htmlsingle/#features.testing.testcontainers.at-development-time.dynamic-properties)
The Pulsar example i can not get to run on my machine, caused by this [bug](https://github.com/apache/pulsar/issues/20282) 
Can you provide further information about your issue and probably some logs? Your logs should contain some insights about what testcontainers is up to, similar to the following `tc.rabbitmq:3.11-alpine                  : Pulling docker image: rabbitmq:3.11-alpine. Please be patient; this may take some time but only needs to be done once.`

**Comment by eddumelendez** [comment]
I have another example. See https://github.com/eddumelendez/spring-boot-sqs-testcontainers-reusable-mode

In summary, @RestartScope works with existing supported ServiceConnections but not when used along with DynamicProperties. Not close at the comouter right now but in those scenarios is like Testcontainers is ignored and not picked up. You should be able to reproduce with this last example. If needed I can attch logs later.

**Comment by nedimAT** [comment]
Thanks, with that example i can reproduce it. I will start looking into it.

**Comment by nedimAT** [comment]
Hello @philwebb could you provide me with some hint where i should start. What i know so far is, that `@RestartScope` on its own is not enough for the Container to be started. One needs additionally `@Scope` or `@ServiceConnection`, but then the Container will restart with the Application. I searched now for some time in the `DefaultListableBeanFactory` for clues but i think i am stuck.

**Comment by eddumelendez** [comment]
I found that when the bean is annotated with `@RestartSCope`, [this line](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/lifecycle/TestcontainersLifecycleBeanFactoryPostProcessor.java#L44) returns empty and [TestcontainersPropertySourceAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/1a207ed871701a0c889a6b40408702987bf29636/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/properties/TestcontainersPropertySourceAutoConfiguration.java#L32) is not being called. Hope that helps.

**Comment by eddumelendez** [comment]
If the line previously mentioned is changed to `beanFactory.getBeanNamesForType(Startable.class, true, false)`, including non singletons then the container bean is taken.

**Comment by eddumelendez** [comment]
I did another check and wonder if just changing the following lines 

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/lifecycle/TestcontainersLifecycleBeanPostProcessor.java#L84-L85

to

```java
beanNames.addAll(List.of(this.beanFactory.getBeanNamesForType(ContainerState.class, true, false)));
beanNames.addAll(List.of(this.beanFactory.getBeanNamesForType(Startable.class, true, false)));
```

due to the scope is not `singleton` anymore but `restart`.

**Comment by Wzy19930507** [comment]
> I have another example. See https://github.com/eddumelendez/spring-boot-sqs-testcontainers-reusable-mode

Hi, @eddumelendez, @philwebb 
`DynamicPropertyRegistry` init property before `SqsAsyncClient`

but when add `RestartScope`, scope change to restart, will [skip this logic
](https://github.com/spring-projects/spring-framework/blob/5856d2e54efe9209e415b0547174cd754473d6cc/spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java#L967) because bean is not singleton, and `DynamicPropertyRegistry` init property after `SqsAsyncClient`

**Comment by philwebb** [comment]
Thanks [for the hint](https://github.com/spring-projects/spring-boot/issues/35786#issuecomment-1636713082) @eddumelendez. Hopefully fixed in the next snapshot.

**Comment by eddumelendez** [comment]
Thanks @philwebb ! It's working :)

**Comment by shawnweeks** [comment]
I've been following this ticket since before it got renamed and with the latest 3.3.2-SNAPSHOT The combination of `@RestartScope` and `DynamicPropertyRegistry` does work on startup but all the properties get unset after dev-tools reloads the app. Previously the properties didn't get set at all so it's definitely an improvement but I'm not sure this fully fixes the issue.

**Comment by scottfrederick** [comment]
@shawnweeks Does the discussion in #35200 and the documentation changes made in [this related commit](https://github.com/spring-projects/spring-boot/commit/1504e3043d8e134f90143239995ff141c86af7bc) help with your use case?

**Comment by shawnweeks** [comment]
@scottfrederick  They don't appear to. This issue was originally about `Contributing Dynamic Properties at Development Time is not working with @RestartScope` which is what still doesn't seem to be working. This issue seems to resolve part of the original issue but dynamic properties still don't fully work with RestartScope. Don't mind starting another ticket just don't want it to get closed as duplicate since this ticket appeared to be trying to resolve the same issue.
