### ISSUE TITLE
Logging in Launcher prevents use of a custom JUL LogManager

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3815]
http://stackoverflow.com/questions/32161616/java-util-logging-redirection-to-log4j2-not-working-for-spring-boot-applications/32163780

**Comment by mrumpf** [comment]
The SLF4J API documentation mentions the performance issue when using the SLF4JBridgeHandler: http://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html
Log4j2 provides a much better solution for this by using a custom LogManager:
https://logging.apache.org/log4j/2.0/log4j-jul/index.html
In one of our applications we are using the MS SQL JDBC driver, which also utilizes Java Util Logging internally. Because JDBC logging is usually high-frequency logging we are seeking for a performant way to redirect the logs.

The Log4j2 approach to redirecting JUL is to use a custom LogManager. The issue with a custom LogManager is that the Java Util Logging sub-system must not be initialized before setting the property `java.util.logging.manager`. As soon as the first `java.util.logging.Logger` is accessed, the JUL logging sub-system gets initialized and there is no way to change the LogManager anymore.

As far as I know there are 3 different ways to start a Spring Boot application:
**1. Spring Tool Suite (STS)**
STS uses the usual Eclipse way and assembles the classpath, based on the Eclipse internal model. There is no issue here because no special Launcher is used and the Main-Class is invoked directly, where I call a `System.setProperty("java.util.logging.manager", "org.apache.logging.log4j.jul.LogManager")` to install the custom LogManager.

**2. Spring Boot Maven Plugin**
The Maven Plugin uses the Maven Plexus IoC container to assemble the classpath. Unfortunately the Plexus Container uses Google Guice, which uses JUL for logging. That means the usual JDK LogManager is already installed when the Main-Class gets invoked. In this case JUL statments will end up at STDOUT. A workaround for this is to configure the Maven plugin, setting the fork mode to true: `<fork>true</fork>`. When the application is started in a separate process, the Main-Class for this process gets invoked immediately without some container initialization before.

**3. Command Line**
When invoked via the command line `java -jar myapp.jar` the Spring Boot Launcher is used to assemble the classpath from the internal JAR's lib folder. Unfortunately the Spring Launcher also uses Java Util Logging for a few diagnostic messages so that the LogManager is already initailized with the usual JDK LogManager implementation.

The suggestion is to drop the use of Java Util Logging for the Spring Boot Launcher and to dump any diagnostic messages to STDERR or STDOUT. This would postpone the Java Util Logging initialization until the Main-Class gets invoked, where you can set the system property to make the JUL redirection work `System.setProperty("java.util.logging.manager", "org.apache.logging.log4j.jul.LogManager")`.

**Comment by mrumpf** [comment]
I have implemented  a deferred logging as you suggested.
Please review the following commit: https://github.com/mrumpf/spring-boot/commit/457d082fe7962c78c17bb18b24cbf177f6efdf5e
I have not yet created a pull request because I'm waiting for PR #4367 to be merged. The changes for enabling the build behind a proxy is also on my gh-3815 branch and if I send the PR for gh-3815 now it will include the proxy changes. See the commit message and the Javadoc for documentation

**Comment by philwebb** [comment]
Outcome: Remove all logging from Launcher in 1.4, deprecate in 1.3.

**Comment by mrumpf** [comment]
Thanks for the info. To remove JDK logging from the Launcher was my preferred solution.

**Comment by aaronjwhiteside** [comment]
This is still an issue on `1.5.2.RELEASE`

`java -Dserver.port=8090 -Dmanagement.port=8091 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -jar rest-example-1.0.0-SNAPSHOT.war`

```
Could not load Logmanager "org.apache.logging.log4j.jul.LogManager"
java.lang.ClassNotFoundException: org.apache.logging.log4j.jul.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.util.logging.LogManager$1.run(LogManager.java:195)
	at java.util.logging.LogManager$1.run(LogManager.java:181)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at java.util.logging.Logger.demandLogger(Logger.java:448)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.springframework.boot.loader.jar.Handler.<init>(Handler.java:74)
	at org.springframework.boot.loader.jar.JarFile.getUrl(JarFile.java:312)
	at org.springframework.boot.loader.archive.JarFileArchive.getUrl(JarFileArchive.java:74)
	at org.springframework.boot.loader.Launcher.createClassLoader(Launcher.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
```

Contents of the executable .war:
```
...
WEB-INF/lib-provided/log4j-web-2.8.jar
WEB-INF/lib-provided/log4j-api-2.8.jar
WEB-INF/lib-provided/log4j-core-2.8.jar
WEB-INF/lib-provided/disruptor-3.3.6.jar
WEB-INF/lib-provided/log4j-1.2-api-2.8.jar
WEB-INF/lib-provided/log4j-jcl-2.8.jar
WEB-INF/lib-provided/commons-logging-1.2.jar
WEB-INF/lib-provided/log4j-jul-2.8.jar
WEB-INF/lib-provided/log4j-slf4j-impl-2.8.jar
...
```

**Comment by philwebb** [comment]
@aaronjwhiteside Could you please open a new issue for this and provide a sample application that shows the problem?

**Comment by pwielgolaski** [comment]
@philwebb, I have the same problem and based on call stack it seems that Handler is problematic piece.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/Handler.java#L74

**Comment by wilkinsona** [comment]
@pwielgolaski Echoing what while [said above](https://github.com/spring-projects/spring-boot/issues/3815#issuecomment-286316727), could you please open a new issue for this and provide a sample application that shows the problem?
