### ISSUE TITLE
spring.profiles.active in default properties ignored if defaultProperties contain a value for that key

### ISSUE THREAD

**Issue by deepu105** [spring-projects/spring-boot#5998]
As per documentation [here](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties) a boot application is suppose to override properties that is defined in files in the given order.

So consider this situation.

I define `spring.profiles.active` and set it to `dev` using `SpringApplication.setDefaultProperties` which is last in the order. So that my application always has a profile by default.

Now I set `spring.profiles.active` to `prod`  in my `application.yml` file and since its in a higher order I would expect this to override what I set earlier above.

But thats not happening, My application doesnt take prod profile and I see this debug log
```
com.mycompany.myapp.TestApp              : Starting TestApp on DESKTOP-3NUQHBI with PID 14436 (D:\Projects\test\testApp\target\classes started by Deepu in D:\Projects\test\testApp)
2016-05-20 17:07:48.045 DEBUG 14436 --- [  restartedMain] com.mycompany.myapp.TestApp              : Running with Spring Boot v1.3.5.RELEASE, Spring v4.2.6.RELEASE
2016-05-20 17:07:48.046  INFO 14436 --- [  restartedMain] com.mycompany.myapp.TestApp              : The following profiles are active: dev
2016-05-20 17:07:48.046 DEBUG 14436 --- [  restartedMain] o.s.boot.SpringApplication               : Loading source class com.mycompany.myapp.TestApp
2016-05-20 17:07:49.085 DEBUG 14436 --- [  restartedMain] o.s.b.c.c.ConfigFileApplicationListener  : Activated profiles dev
2016-05-20 17:07:49.100 DEBUG 14436 --- [  restartedMain] o.s.b.c.c.ConfigFileApplicationListener  : Profiles already activated, '[prod]' will not be applied
2016-05-20 17:07:49.100 DEBUG 14436 --- [  restartedMain] o.s.b.c.c.ConfigFileApplicationListener  : Loaded config file 'classpath:/config/application.yml'
2016-05-20 17:07:49.100 DEBUG 14436 --- [  restartedMain] o.s.b.c.c.ConfigFileApplicationListener  : Loaded config file 'classpath:/config/application-dev.yml'
2016-05-20 17:07:49.151 DEBUG 14436 --- [  restartedMain] o.s.b.c.c.ConfigFileApplicationListener  : Skipped (empty) config file 'classpath:/config/application-dev.yml' for profile dev
2016-05-20 17:07:49.152 DEBUG 14436 --- [  restartedMain] o.s.b.c.c.ConfigFileApplicationListener  : Skipped (empty) config file 'classpath:/config/application.yml' for profile dev
```

But if I set  `spring.profiles.active` to `prod` in Command line arguments its working as expected.

I would assume that this is a bug as the behaviour is different from what is documented.

**Comment by philwebb** [comment]
Are you able to share a sample project we can try?

**Comment by deepu105** [comment]
Ok, ill push one, we were trying to fix an issue in JHipster when I noticed this.

**Comment by deepu105** [comment]
Here is the sample app generated using JHipster https://github.com/deepu105/jhipster-sample

The default profile is set [here](https://github.com/deepu105/jhipster-sample/blob/master/src/main/java/com/mycompany/myapp/TestApp.java#L68) by calling [this](https://github.com/deepu105/jhipster-sample/blob/master/src/main/java/com/mycompany/myapp/TestApp.java#L84)  method.

Then im trying to overwrite that [here](https://github.com/deepu105/jhipster-sample/blob/master/src/main/resources/config/application.yml#L27)

But I always get whatever profile I set in the main application class

**Comment by snicoll** [comment]
What happens is that we start reading from the default configuration file for a profile declaration only if no profile is active. You set one yourself explicitly so we're bypassing that mechanism. It's a bit weird, I reckon.

I had a quick look to your sample and the commented code is wrong IMO. We have implemented a `default` profile for quite some time that does what you want: independently of this being addressed, it would be nicer than your current solution. 

Just set this in default properties:

```
app.setDefaultProperties(Collections.singletonMap("spring.profiles.default", "dev"));
```

Then you'll get the following if no override is set

```
com.example.DemoApplication              : No active profile set, falling back to default profiles: dev
```

and the following with an override

```
com.example.DemoApplication              : The following profiles are active: prod
```

Your sample works with that solution. Please give a try.

**Comment by snicoll** [comment]
I think the current situation is a bit convoluted and we should probably read from the default properties before figuring out which profiles are _actually_ active. This would make the implementation more complicated, obviously.

**Comment by deepu105** [comment]
@snicoll Indeed that was my original solution to use `spring.profiles.default` and set it to `dev` using `setDefaultProperties`. That's what the commented line was doing. But this had another issue, the dev profile was always being loaded along with whatever active profile I set and somehow I was still getting dev profile DB properties when `spring.profiles.active` is set to `prod` in code [here](https://github.com/deepu105/jhipster-sample/blob/master/src/main/java/com/mycompany/myapp/config/DatabaseConfiguration.java#L49). That is the reason I tried to set `spring.profiles.active` instead. I'm not sure if this was intended behavior or a bug in itself.

**Comment by deepu105** [comment]
In order to simulate the above just do the below in the sample I gave. I guess point 1 and 2 is obvious to you :)

1. Un comment[ this line](https://github.com/deepu105/jhipster-sample/blob/master/src/main/java/com/mycompany/myapp/TestApp.java#L91)
2. Comment out [this line](https://github.com/deepu105/jhipster-sample/blob/master/src/main/java/com/mycompany/myapp/TestApp.java#L94)
3. Run the app. `dev` profile is configured to use a H2 DB, `prod `profile is configured to use a MySQL DB, so if you dont have a MySQL instance running you should ideally get an error and app shouldnt start as we have set `prod `profile in `application.yml` file. But in the given sample with above 2 modification you would see that the app starts without error and if you check you cans see its running H2 DB from the dev profile.

I debugged to check and I found that it was loading dev DB details [here](https://github.com/deepu105/jhipster-sample/blob/master/src/main/java/com/mycompany/myapp/config/DatabaseConfiguration.java#L49) which might be something wrong with our config but on inspecting the environment I could see that it has loaded `application.yml`, `application-dev.yml` and `application-prod.yml` when `spring.profiles.active` is set to `prod` and `spring.profiles.default` is set to `dev`. If I remove `spring.profiles.default` then  `application-dev.yml`  is not loaded and I get proper DB config

**Comment by deepu105** [comment]
btw thanks for looking into this @snicoll :smile:

**Comment by philwebb** [comment]
Looking into this a bit more, I'm not sure if the initial issue is something we should try to change. Although configuration order is [defined](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config) such that `application.properties` override `setDefaultProperties`, the order during load is actually a little tricky.

We have the following logic in `ConfigFileApplicationListener` which specifically allows active profiles in the `Environment` to take precedence:

```java
private Set<String> initializeActiveProfiles() {
	if (!this.environment.containsProperty(ACTIVE_PROFILES_PROPERTY)) {
		return Collections.emptySet();
	}
	// Any pre-existing active profiles set via property sources (e.g. System
	// properties) take precedence over those added in config files.
	Set<String> activeProfiles = getProfilesForValue(
			this.environment.getProperty(ACTIVE_PROFILES_PROPERTY));
	maybeActivateProfiles(activeProfiles);
	return activeProfiles;
}
```

Changing that logic is likely to break existing applications, possibly in very unexpected ways.

I'm still digging into the `spring.profiles.default` issue.

**Comment by philwebb** [comment]
With the `spring.profiles.default`, it appears that the `prod` profile being activated in `application.properties` is causing both profiles to be loaded. I guess you could argue that if a profile is activated in `application.properties` then the default one should back off (so that's probably a bug).

**Comment by philwebb** [comment]
@deepu105 Can we back up a bit with this issue. What is it that you are actually trying to achieve? Are you wanting a `dev` profile to be activated only if the user doesn't specify `spring.profiles.active` on the command line? What's the reason that the `prod` profile is activated in `application.yml`?

**Comment by deepu105** [comment]
@philwebb for JHipster we are generating apps with a `dev` and `prod` profile. so when users build using `dev` profile we set that as the default profile and when they build using `prod` profile we set that as default. this enables the user to run the built jar/war without having to specify any profile as they specified the profile during build time already. So when there is no explicit profile set we want the `dev` profile to be the default and thats why we tried this. but since this wasnt working as we expected we currently read the `application.yml` manually and set the profile manually here https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_DefaultProfileUtil.java#L31

**Comment by deepu105** [comment]
so basically what we want is to have a default profile when there is no profile set in `application.yml` or in the environment

**Comment by snicoll** [comment]
more specifically you want that and you want to be able to customize the name of that profile (it's `default` and you want to name it `dev`).

**Comment by deepu105** [comment]
in a way yes

**Comment by snicoll** [comment]
Sorry to insist but in one way isn't that the case? I am trying to confirm that if your `dev` profile was named `default` everything would work as expected for you.

**Comment by deepu105** [comment]
@snicoll I understand that but I dont think thats feasible in JHipster for aesthetic reasons. in that case what is the purpose of `spring.profiles.default`?

**Comment by snicoll** [comment]
I am not asking you to change anything. I am asking you if that statement is true or not to confirm we fully understood the problem.

**Comment by deepu105** [comment]
@snicoll oh sorry. Yes you are right.

**Comment by philwebb** [comment]
I think I have a fix for the `spring.profiles.default` issue. My branch [is here](https://github.com/philwebb/spring-boot/tree/gh-5998). I need to get the code reviewed by @snicoll or @wilkinsona before merging.

**Comment by deepu105** [comment]
Thank you @philwebb and @snicoll . will give it a try soon

**Comment by deepu105** [comment]
@philwebb @snicoll I tried this and this is working for the most part. There is one small glitch though consider the below

1. I have two profiles `dev` and `prod`
2. I have set `spring.profiles.default` to `dev` using 
```
public static void addDefaultProfile(SpringApplication app) {
        Map<String, Object> defProperties =  new HashMap<>();
        defProperties.put("spring.profiles.default", "dev");
        app.setDefaultProperties(defProperties);
    }
```
Note: Im not using `Collections.singletonMap` as its makes the array fixed size, which causes issues as you guys would try to add stuff to that array in spring
3. Now if I do `env.acceptsProfiles("dev")` it will return false, which is ok since I didnt set it as active profile
4. now if I do `--spring.profiles.active=dev` I would expect `env.acceptsProfiles("dev")` to return true but it doesnt. seems like if the same profile is used as active and default the default one is used. Ideally it should be promoted to active

The usecase for this is if I want to do some stuff based on profiles I might be using `env.acceptsProfiles("dev")` to check if the profile is active and in this case its failing.

**Comment by deepu105** [comment]
A test case for the scenario would be
```
        @Test
 	public void sameDefaultProfileAndActive() throws Exception {
 		SpringApplication application = new SpringApplication(Config.class);
 		application.setWebEnvironment(false);
 		this.context = application.run("--spring.profiles.default=customdefault",
 				"--spring.profiles.active=customdefault");
 		assertThat(this.context.getEnvironment().acceptsProfiles("customdefault"))
 				.isTrue();
 	}

```

**Comment by philwebb** [comment]
@deepu105 Since this issue has been closed already, you please raise a fresh one for your related problem.

**Comment by deepu105** [comment]
Ok sure

Thanks & regards,
Deepu

**Comment by huangyiminghappy** [comment]
use like this can resolve `<context:property-placeholder location="classpath:application.properties" order="1" />
	<context:property-placeholder location="classpath:application-${spring.profiles.active}.properties" ignore-resource-not-found="true" order="2" ignore-unresolvable="true" />`
