### ISSUE TITLE
Application Startup issue (java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy) with Spring boot 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by brsanthu** [spring-projects/spring-boot#8667]
Here is the system info.
```
$ uname -a; java -version
Darwin sanbook.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro13,3 Darwin
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

`Spring boot 2.0.0-SNAPSHOT`

When we start the app we get below error. I guess this is due some internal restructure that is going on in 2.0.0. So far I have been able to keep our app running by referring to newer classes but not getting path forward with this. Appreciate your help in this.

<pre><code>java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:102)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:47)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:243)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:96)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$null$1(ClassTestDescriptor.java:196)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.executeAndMaskThrowable(JupiterTestDescriptor.java:102)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeTestInstancePostProcessors$2(ClassTestDescriptor.java:196)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestInstancePostProcessors(ClassTestDescriptor.java:195)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstanceProvider$0(ClassTestDescriptor.java:187)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.prepare(MethodTestDescriptor.java:120)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.prepare(MethodTestDescriptor.java:63)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:59)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:129)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.runner.JUnitPlatform.run(JUnitPlatform.java:116)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1648)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:484)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:865)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:809)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:347)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:128)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 37 moreCaused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:599)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:173)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:213)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:184)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1644)
	... 53 more
</code></pre>

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the problem?

**Comment by spencergibb** [comment]
I also had this problem. For my project, it was caused when a class was not available in a conditional on bean annotation. Specifically classes recently moved in boot 2.0.

**Comment by spencergibb** [comment]
@wilkinsona here are some changes that fixed the issue for me:

- https://github.com/spring-cloud/spring-cloud-netflix/commit/4b4bfbe1b109a5c6e1a603d7ff2ef71feab6f9cb#diff-d9fea25312b595e50d443cfc808ea4c2R68
- https://github.com/spring-cloud/spring-cloud-commons/commit/d11abd8f5e8f238aa833f232ea1c514682897cfa#diff-dc3efddce7cc10070897e1bca6d2ddf2R8
- https://github.com/spring-cloud/spring-cloud-commons/commit/d11abd8f5e8f238aa833f232ea1c514682897cfa#diff-d442f2e7eb3d05136f5c54e9b7c74efdR26

**Comment by brsanthu** [comment]
I created a sample test barebone app with 2.0.0 dependency and it is starting fine. So I guess this is is an issue when combined with other dependencies. Trying to figure out what is that dependency.

**Comment by brsanthu** [comment]
This is happening when I include the spring cloud config dependency into the app.

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
            <version>1.2.3.RELEASE</version>
        </dependency>
```

**Comment by philwebb** [comment]
@brsanthu Spring Cloud isn't compatible with the Spring Boot 2.0 SNAPSHOT. Is there any specific reason you're trying the SNAPSHOTs over the RELEASE version?

**Comment by brsanthu** [comment]
No particular reason, as it was working earlier, it is as is. I can update to snapshot of cloud config if there is one.

Are you aware of cloud config version which is compatible with boot 2.0.0?

**Comment by philwebb** [comment]
@brsanthu You're probably going to find the SNAPSHOTs quite a bumpy ride for the next few months. If you're trying to write production code I'd strongly recommend sticking to `RELEASE` versions.

@spencergibb can probably give an update on the Spring Cloud situation. We'll also be releasing milestones for Spring Boot 2.0 fairly soon.

**Comment by brsanthu** [comment]
@philwebb thank you. We were expecting it is going to be bumpy ride but as our planned release is after Boot planned release, we were trying to use it. I think based on your advice, we will try to revert to 1.5.3.

Appreciate your help.

**Comment by spencergibb** [comment]
@brsanthu we just pushed some commits to some spring-cloud modules (commons, config and netflix) at version 2.0.0.BUILD-SNAPSHOT as part of the Finchley Release Train scheduled for the end of the year. We'll follow the first boot milestone, by a couple of weeks.

**Comment by tunovic** [comment]
I am not sure if this one is related to https://stackoverflow.com/questions/40569343/cucumber-test-for-spring-boot-can-run-in-mvn-test-but-not-in-mvn-verify
I am experiencing same problem where I just add spring-boot-maven-plugin without any executions. Java 9 (181), Maven 3.5.0, Spring Boot 2.0.0.M5 and Cucumber 1.2.5
I do have Cucumber running in integration-test phase.

**Comment by bclozel** [comment]
@tunovic If you don't have Spring Cloud on your classpath and you're running Cucumber tests on Java 9, then it doesn't look like it's related at all. Before you create another Boot issue, I'd first check that Cucumber actually supports JDK9.

**Comment by deki** [comment]
@spencergibb  it should work using 2.0.0.M2 shouldn't it? I'm still seeing this error in this version when HystrixAutoConfiguration is parsed.

**Comment by binkley** [comment]
How is this going?  It happens to me with M7 -- https://github.com/binkley/sproingk/tree/3048744c760b5628f5d14e8e3a82d25c8115f626

**Comment by wilkinsona** [comment]
@binkley From a Spring Boot perspective, there's nothing going here. The problem, which I believe as now been resolved, was in Spring Cloud. I've checked out the revision of Sproink that you've linked to. Its 11 tests all pass. I also can't see any usage of Spring Cloud so, whatever the problem is that you're facing, it wasn't the one reported in this issue.
